# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-23 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('director', models.CharField(max_length=128)),
                ('year', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('synopsys', models.CharField(max_length=128)),
                ('actors', models.CharField(max_length=4096)),
            ],
        ),
    ]
